//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServidor
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.Inscrito = new ObservableCollection<Inscrito>();
        }
    
        public string ClaveG { get; set; }
        public string Salón { get; set; }
        public Nullable<short> IdProf { get; set; }
        public short ClaveM { get; set; }
    
        public virtual Mater Mater { get; set; }
        public virtual Prof Prof { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Inscrito> Inscrito { get; set; }
    }
}
