//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServidor
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Historial
    {
    public Historial(){

    }
    public Historial(int folio, short calif, DateTime fecha, short cu, short clavem) {
      Folio = folio;
      Calif = calif;
      Fecha = fecha;
      CU = cu;
      ClaveM = clavem;
    }

    public int Folio { get; set; }
        public Nullable<short> Calif { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public short CU { get; set; }
        public short ClaveM { get; set; }
    
        public virtual Alum Alum { get; set; }
        public virtual Mater Mater { get; set; }
    }
}
