//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServidor
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Inscrito
    {
        public short CU { get; set; }
        public string ClaveG { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Alum Alum { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
