//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServidor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaEscolarEntities : DbContext
    {
        public SistemaEscolarEntities()
            : base("name=SistemaEscolarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alum> Alum { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Inscrito> Inscrito { get; set; }
        public virtual DbSet<Mater> Mater { get; set; }
        public virtual DbSet<Prof> Prof { get; set; }
    }
}
