//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pregunta1_182671
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int FolioP { get; set; }
        public int IdArt { get; set; }
        public Nullable<int> CantPed { get; set; }
        public Nullable<int> CantEnt { get; set; }
    
        public virtual Artículos Artículos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
