//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pregunta1_182671
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReAbast
    {
    private int folio;
    private object p;

    public ReAbast(int folio, int cant, int monto, DateTime fechaped, object p, int idArt) {
      this.folio = folio;
      Cant = cant;
      Monto = monto;
      FechaPed = fechaped;
      this.p = p;
      IdArt = idArt;
    }

    public int FolioR { get; set; }
        public Nullable<int> Cant { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaPed { get; set; }
        public Nullable<System.DateTime> FechaEnt { get; set; }
        public int IdArt { get; set; }
    
        public virtual Artículos Artículos { get; set; }
    }
}
