//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pregunta1_182671
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Rfc { get; set; }
        public string Nombre { get; set; }
        public string Passw { get; set; }
        public string Tipo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
