//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int Folio { get; set; }
        public int IdP { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
    
        public virtual Préstamos Préstamos { get; set; }
    }
}
